name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: user/app:latest
      - name: Test
        run: |
          docker run --rm user/app:latest basic.add 1 2
          docker run --rm user/app:latest aasync.add 1 2
          docker run --rm user/app:latest aasync.compute 1 2
